### PR TITLE
resolved for 017

### PR DESCRIPTION
**Pull request by ProjectTAL**
Hi Derek,

I just resolved for 017 problem, which is "사용자의 나이를 묻자. 만약 18세 이상이면 "You can vote"라는 메시지를 표시하라. 만약 17세라면 "You can learn to drive"라는 메시지를 표시하라. 만약 16세라면 "You can buy a lottery tick"이라는 메시지를 표시하라. 만약 16세 미만이라면 "You can go Trick-or-Treating"이라는 메시지를 표시하라".
So If you have a chance to review my change, I hope you would approve this as well.

Thanks,
Ethan

### CODE REVIEW

**Comment by ProjectTAL** [comment]
This notification sent to you, Derek?

**Comment by ProjectTAL** [comment]
> Hi Derek,
> 
> I just resolved for 017 problem, which is "사용자의 나이를 묻자. 만약 18세 이상이면 "You can vote"라는 메시지를 표시하라. 만약 17세라면 "You can learn to drive"라는 메시지를 표시하라. 만약 16세라면 "You can buy a lottery tick"이라는 메시지를 표시하라. 만약 16세 미만이라면 "You can go Trick-or-Treating"이라는 메시지를 표시하라". So If you have a chance to review my change, I hope you would approve this as well.
> 
> Thanks, Ethan

**Review by dr-robo — APPROVED** [review]
GOOD!!!

**Review by dr-robo — APPROVED** [review]
good

**Review by dr-robo — APPROVED** [review]
good

**Pull request merged**
